### PR TITLE
return npm username also

### PR DESCRIPTION
**Pull request by alefteris**
Added the npm username to the returned object, as it think most users will want to keep/save it together with the rest of the properties.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? You already know the username.

**Comment by alefteris** [comment]
Yes, but it's extra work to add it with the rest of the properties. Also usually when you make a call to an API by some ID, the ID is usually returned as part of the results.

Bellow is an example for my code. If I had to add the username as an extra step, it would complicate things. Or maybe I just don't know how to use Promises?  :worried:

```
const Promise = require("bluebird");
const npmUser = require('npm-user');

...

fs.readFileAsync('/a/path', 'utf8')
  .then(parseUsernames)
  .map(npmUser, {concurrency: 5})
  .then(profile => JSON.stringify(profile, null, 2))
  .then(profilesJson => fs.writeFileSync(outputPath, profilesJson))
...
```

**Comment by SamVerschueren** [comment]
Honestly, I don't see the added value of this. It's a specific use case which can be easily solved by the user of the library (you in this case).

```js
function parseUsernames (list) {
    return list.map(user => {
        return npmUser(user).then(result => Object.assign(result, {username: user}));
    });
}
```

**Comment by alefteris** [comment]
Thanks for the example @SamVerschueren . Sorry if I wasted everyone's time.

**Comment by SamVerschueren** [comment]
No problem. Every change is worth a discussion :).

**Pull request closed without merging**
